package command

const (
	langFlag            = "lang"
	dirFlag             = "dir"
	bundleFlag          = "bundle"
	namespaceFlag       = "namespace"
	branchFlag          = "branch"
	methodFlag          = "method"
	versionFlag         = "version"
	repoFlag            = "repo"
	typeFlag            = "type"
	environmentFlag     = "environment"
	updateTemplatesFlag = "update-templates"
	preReleaseFlag      = "prerelease"
	dryRunFlag          = "dryrun"
	resetFlag           = "reset"
	localFlag           = "local"
	proxyPortFlag       = "proxy-port"
	domainFlag          = "domain"
	appNameFlag         = "app-name"
	httpPortFlag        = "http-port"
	tlsPortFlag         = "tls-port"
	runPartnerFlag      = "run"
	orgFlag             = "org"
	regionFlag          = "region"
	preBuildFlag        = "pre-build"
)
