name: tinygo-base

on:
  pull_request:
    paths:
      - .github/workflows/tinygo-base.yml
      - builder/docker/tinygo/Dockerfile.base

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1

      - uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: builder/docker/tinygo/Dockerfile.base
          platforms: ${{ matrix.platform }}
          tags: suborbital/tinygo-base:test
